name: test-env
on: [push]

jobs:
  install-dependencies:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: '18'
      - run: npm install
      - run: npm test
